import { ChatPanel, ChatMessage } from './ChatPanel';
import { Download } from 'lucide-react';

interface EditingStepProps {
  documentHtml: string;
  fileName: string;
  chatMessages: ChatMessage[];
  isChatLoading: boolean;
  streamingContent: string;
  onSendChatMessage: (message: string) => void;
  onSubmitForReview: () => void;
  onExport: () => void;
}

export function EditingStep({
  documentHtml,
  fileName,
  chatMessages,
  isChatLoading,
  streamingContent,
  onSendChatMessage,
  onSubmitForReview,
  onExport,
}: EditingStepProps) {
  return (
    <div className="flex-1 flex h-full min-h-0">
      {/* Left: Document preview */}
      <div className="flex-1 flex flex-col min-w-0 border-r border-border">
        <div className="px-6 py-3 border-b border-border bg-card flex items-center justify-between">
          <div>
            <p className="text-xs text-muted-foreground uppercase tracking-widest">Live Preview</p>
            <h2 className="text-sm font-semibold text-foreground">{fileName || 'Document'}</h2>
          </div>
        </div>
        <div className="flex-1 overflow-y-auto doc-scroll bg-background">
          <div className="max-w-3xl mx-auto py-12 px-16">
            {documentHtml ? (
              <div
                className="prose prose-sm max-w-none text-foreground
                  [&_h1]:text-2xl [&_h1]:font-bold [&_h1]:mb-4
                  [&_h2]:text-xl [&_h2]:font-semibold [&_h2]:mb-3
                  [&_h3]:text-lg [&_h3]:font-medium [&_h3]:mb-2
                  [&_p]:mb-3 [&_p]:leading-relaxed
                  [&_table]:border-collapse [&_table]:w-full [&_table]:mb-4
                  [&_td]:border [&_td]:border-border [&_td]:px-3 [&_td]:py-2 [&_td]:text-sm
                  [&_th]:border [&_th]:border-border [&_th]:px-3 [&_th]:py-2 [&_th]:text-sm [&_th]:font-semibold [&_th]:bg-muted
                  [&_ul]:list-disc [&_ul]:pl-6 [&_ul]:mb-3
                  [&_ol]:list-decimal [&_ol]:pl-6 [&_ol]:mb-3
                  [&_li]:mb-1"
                dangerouslySetInnerHTML={{ __html: documentHtml }}
              />
            ) : (
              <div className="flex items-center justify-center h-64">
                <p className="text-muted-foreground text-sm">
                  Document will appear here once generated by DocuWise.
                </p>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Right: Chat */}
      <div className="w-[380px] flex-shrink-0">
        <ChatPanel
          messages={chatMessages}
          isLoading={isChatLoading}
          streamingContent={streamingContent}
          onSendMessage={onSendChatMessage}
          title="Legal Editor"
          subtitle="Request changes or ask about clauses"
          placeholder="Ask about the document or request changes..."
          actions={
            <div className="flex items-center gap-2">
              <button
                onClick={onExport}
                className="flex items-center gap-1.5 px-3 py-1.5 text-xs rounded-md bg-chat-muted text-chat-foreground/70 hover:text-chat-foreground transition-colors"
              >
                <Download className="w-3 h-3" />
                .docx
              </button>
              <button
                onClick={onSubmitForReview}
                className="px-3 py-1.5 text-xs rounded-md bg-primary text-primary-foreground hover:bg-primary/90 transition-colors font-medium"
              >
                Submit for Review
              </button>
            </div>
          }
        />
      </div>
    </div>
  );
}
